name: egu22pygmt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.3.0
  - jupyterlab=3.4.0
  - pygmt=0.6.1
  - python=3.9
  # Optional dependencies
  - geopandas=0.10.2
  - jupyter-book=0.12.3
  - laspy=2.1.2
  - rioxarray=0.11.1
  - pip:
    - lazrs==0.4.1
